#!/bin/bash
# 🌱 Complete Fennel Validator Registration
# Generates stash account and prepares final submission for Fennel Labs

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

echo -e "${BLUE}🌱 Fennel Validator Registration Completion${NC}"
echo "=============================================="
echo

# Check if session keys exist
if [ ! -f "session-keys.json" ]; then
    log_error "Session keys not found."
    echo -e "${YELLOW}Please run: ./scripts/generate-session-keys.sh${NC}"
    exit 1
fi

# Generate stash account if it doesn't exist
if [ ! -f "stash-account.json" ]; then
    log_info "Generating stash account for validator registration..."
    
    # Check if we have the generate-stash-account.sh script
    if [ -f "tools/internal/generate-stash-account.sh" ]; then
        cd tools/internal
        ./generate-stash-account.sh
        cd ../..
    else
        log_error "Stash account generation script not found"
        exit 1
    fi
fi

# Read session keys and stash account information
VALIDATOR_NAME=$(jq -r '.validator_name' session-keys.json)
SESSION_KEYS=$(jq -r '.session_keys' session-keys.json)
STASH_ADDRESS=$(jq -r '.stash_account.ss58_address' stash-account.json)
STASH_SECRET=$(jq -r '.stash_account.secret_phrase' stash-account.json)

# Create complete submission file
log_info "Creating complete submission for Fennel Labs..."

cat > COMPLETE-REGISTRATION-SUBMISSION.txt << EOF
╔══════════════════════════════════════════════════════════════════╗
║           🌱 FENNEL VALIDATOR REGISTRATION COMPLETE 🌱           ║
╚══════════════════════════════════════════════════════════════════╝

VALIDATOR INFORMATION:
=====================
Validator Name: $VALIDATOR_NAME
Network: Fennel Solonet (Staging)
Setup Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

CRITICAL INFORMATION FOR FENNEL LABS:
=====================================

🏦 STASH ACCOUNT (Please register this as validator):
SS58 Address: $STASH_ADDRESS
Secret Phrase: $STASH_SECRET

🔑 SESSION KEYS (Already generated and secured):
$SESSION_KEYS

📋 REGISTRATION PROCESS:
=======================
1. [FENNEL LABS] Send testnet tokens to stash account: $STASH_ADDRESS
2. [VALIDATOR] Call session.setKeys() to bind session keys to stash account
3. [VALIDATOR] Notify Fennel Labs when setKeys() is complete
4. [FENNEL LABS] Register stash account as validator in network

🔒 SECURITY STATUS:
==================
✅ Validator running with security hardening
✅ Session keys generated and secured
✅ Stash account created and ready
✅ Firewall configured (P2P open, RPC/metrics local only)
✅ File permissions secured
✅ Ready for network registration

NEXT STEPS:
===========
1. Send this file to Fennel Labs
2. Wait for testnet tokens
3. Execute session.setKeys() call
4. Await validator registration confirmation

Contact: Generated by secure Fennel validator setup
Repository: https://github.com/CorruptedAesthetic/FennelValidator
EOF

# Create instructions for session.setKeys()
cat > SESSION-SETKEYS-INSTRUCTIONS.txt << EOF
SESSION.SETKEYS() INSTRUCTIONS
=============================

When you receive testnet tokens from Fennel Labs:

1. Go to Polkadot.js Apps: https://polkadot.js.org/apps/
2. Connect to Fennel network using custom endpoint
3. Import your stash account using the secret phrase
4. Navigate to Developer -> Extrinsics
5. Call session.setKeys() with:
   - keys: $SESSION_KEYS
   - proof: 0x (empty proof)
6. Submit transaction and wait for confirmation
7. Notify Fennel Labs that setKeys() is complete

Your stash account: $STASH_ADDRESS
Your secret phrase: $STASH_SECRET
EOF

log_success "Registration files created successfully!"
echo
echo -e "${CYAN}📤 SEND TO FENNEL LABS:${NC}"
echo "  • COMPLETE-REGISTRATION-SUBMISSION.txt"
echo
echo -e "${CYAN}📋 FOR YOUR REFERENCE:${NC}"
echo "  • SESSION-SETKEYS-INSTRUCTIONS.txt"
echo "  • stash-account.json (keep secure!)"
echo "  • session-keys.json (keep secure!)"
echo
echo -e "${YELLOW}🔒 SECURITY REMINDER:${NC}"
echo "Keep your stash account secret phrase secure!"
echo "This is your main validator identity and controls funds."
echo
echo -e "${GREEN}🎉 Registration preparation complete!${NC}" 